import io
import json
import zipfile
from typing import Tuple

from fastapi.responses import StreamingResponse

from src.run_utils.db import get_project_title, load_all_files
from src.run_utils.report import build_report
from src.run_utils.state import get_run


def make_zip_bytes(run_id: str, user: str) -> Tuple[bytes, str]:
    r = get_run(run_id)
    buf = io.BytesIO()
    files = load_all_files(run_id, user)
    title = get_project_title(run_id, user)
    with zipfile.ZipFile(buf, "w", zipfile.ZIP_DEFLATED) as z:
        for path, content in files.items():
            z.writestr(path, content)
        if "mock_html" in r:
            z.writestr("preview-mock.html", r["mock_html"])
        z.writestr(
            "report.json",
            json.dumps(build_report(run_id), ensure_ascii=False, indent=2),
        )
        z.writestr(
            "report.json",
            json.dumps(build_report(run_id), ensure_ascii=False, indent=2),
        )
        z.writestr(
            "README.txt",
            "Generated by your agentic builder. Open index.html locally or in a sandbox.\n",
        )
    buf.seek(0)
    return buf.read(), f"{title}.zip"


def stream_zip_response(run_id: str, user: str) -> StreamingResponse:
    data, name = make_zip_bytes(run_id, user)
    return StreamingResponse(
        io.BytesIO(data),
        media_type="application/zip",
        headers={
            "Content-Disposition": f"attachment; filename={name}",
            "Access-Control-Expose-Headers": "Content-Disposition",
        },
    )
